[0m18:21:10.132488 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106699870>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10756f460>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10756f010>]}


============================== 18:21:10.146286 | 57182bef-7264-490b-b747-3df65ea4b75d ==============================
[0m18:21:10.146286 [info ] [MainThread]: Running with dbt=1.10.1
[0m18:21:10.147399 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/adamworede/.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt init netflix_data', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m18:21:10.199608 [debug] [MainThread]: Starter project path: /Users/adamworede/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dbt/include/starter_project
[0m18:21:10.219313 [info ] [MainThread]: 
Your new dbt project "netflix_data" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m18:21:10.220903 [info ] [MainThread]: Setting up your profile.
[0m18:21:32.435000 [error] [MainThread]: Encountered an error:

[0m18:21:32.446324 [error] [MainThread]: Traceback (most recent call last):
  File "/Users/adamworede/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dbt/cli/requires.py", line 161, in wrapper
    result, success = func(*args, **kwargs)
  File "/Users/adamworede/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dbt/cli/requires.py", line 111, in wrapper
    return func(*args, **kwargs)
  File "/Users/adamworede/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dbt/cli/main.py", line 483, in init
    results = task.run()
  File "/Users/adamworede/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dbt/task/init.py", line 346, in run
    self.setup_profile(profile_name)
  File "/Users/adamworede/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dbt/task/init.py", line 261, in setup_profile
    adapter = self.ask_for_adapter_choice()
  File "/Users/adamworede/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dbt/task/init.py", line 242, in ask_for_adapter_choice
    numeric_choice = click.prompt(prompt_msg, type=click.INT)
  File "/Users/adamworede/.pyenv/versions/3.10.12/lib/python3.10/site-packages/click/termui.py", line 164, in prompt
    value = prompt_func(prompt)
  File "/Users/adamworede/.pyenv/versions/3.10.12/lib/python3.10/site-packages/click/termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m18:21:32.465611 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 22.590853, "process_in_blocks": "0", "process_kernel_time": 0.759269, "process_mem_max_rss": "97058816", "process_out_blocks": "0", "process_user_time": 4.004215}
[0m18:21:32.468086 [debug] [MainThread]: Command `dbt init` failed at 18:21:32.467623 after 22.59 seconds
[0m18:21:32.469733 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106699870>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10756e4d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107560370>]}
[0m18:21:32.471464 [debug] [MainThread]: Flushing usage events
[0m18:21:33.111081 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m18:23:07.552384 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1129697b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x113843970>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x113843520>]}


============================== 18:23:07.564237 | 01bffc59-4262-4a7c-a4eb-6f9dce1babfd ==============================
[0m18:23:07.564237 [info ] [MainThread]: Running with dbt=1.10.1
[0m18:23:07.566115 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '/Users/adamworede/.dbt', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt init netflix_data', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m18:23:07.617258 [debug] [MainThread]: Starter project path: /Users/adamworede/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dbt/include/starter_project
[0m18:23:07.638844 [info ] [MainThread]: 
Your new dbt project "netflix_data" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m18:23:07.640449 [info ] [MainThread]: Setting up your profile.
[0m18:23:14.202847 [error] [MainThread]: Encountered an error:

[0m18:23:14.209144 [error] [MainThread]: Traceback (most recent call last):
  File "/Users/adamworede/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dbt/cli/requires.py", line 161, in wrapper
    result, success = func(*args, **kwargs)
  File "/Users/adamworede/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dbt/cli/requires.py", line 111, in wrapper
    return func(*args, **kwargs)
  File "/Users/adamworede/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dbt/cli/main.py", line 483, in init
    results = task.run()
  File "/Users/adamworede/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dbt/task/init.py", line 346, in run
    self.setup_profile(profile_name)
  File "/Users/adamworede/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dbt/task/init.py", line 261, in setup_profile
    adapter = self.ask_for_adapter_choice()
  File "/Users/adamworede/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dbt/task/init.py", line 242, in ask_for_adapter_choice
    numeric_choice = click.prompt(prompt_msg, type=click.INT)
  File "/Users/adamworede/.pyenv/versions/3.10.12/lib/python3.10/site-packages/click/termui.py", line 164, in prompt
    value = prompt_func(prompt)
  File "/Users/adamworede/.pyenv/versions/3.10.12/lib/python3.10/site-packages/click/termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m18:23:14.214630 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 6.9253874, "process_in_blocks": "0", "process_kernel_time": 0.521933, "process_mem_max_rss": "97964032", "process_out_blocks": "0", "process_user_time": 2.983813}
[0m18:23:14.216074 [debug] [MainThread]: Command `dbt init` failed at 18:23:14.215694 after 6.93 seconds
[0m18:23:14.216758 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1129697b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x113842a10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1138344c0>]}
[0m18:23:14.217359 [debug] [MainThread]: Flushing usage events
[0m18:23:14.923212 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m18:24:09.816764 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10d58d810>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10e463400>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10e462fb0>]}


============================== 18:24:09.824870 | 73aded82-f4b2-400f-9cf1-d4275713b377 ==============================
[0m18:24:09.824870 [info ] [MainThread]: Running with dbt=1.10.1
[0m18:24:09.825617 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '/Users/adamworede/.dbt', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt init netflix_data', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m18:24:09.858816 [info ] [MainThread]: A project called netflix_data already exists here.
[0m18:24:09.864286 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 0.21059191, "process_in_blocks": "0", "process_kernel_time": 0.501758, "process_mem_max_rss": "98381824", "process_out_blocks": "0", "process_user_time": 3.307977}
[0m18:24:09.865331 [debug] [MainThread]: Command `dbt init` succeeded at 18:24:09.865183 after 0.21 seconds
[0m18:24:09.865884 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10d58d810>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10e462f20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10e4624a0>]}
[0m18:24:09.866352 [debug] [MainThread]: Flushing usage events
[0m18:24:10.702899 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m18:24:25.328397 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108ed17e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109da14b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109da1900>]}


============================== 18:24:25.334128 | bcca53a3-d74a-481b-953e-927557dd2644 ==============================
[0m18:24:25.334128 [info ] [MainThread]: Running with dbt=1.10.1
[0m18:24:25.335234 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/adamworede/.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt init netflix_data', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m18:24:25.348642 [debug] [MainThread]: Starter project path: /Users/adamworede/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dbt/include/starter_project
[0m18:24:25.360969 [info ] [MainThread]: 
Your new dbt project "netflix_data" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m18:24:25.361649 [info ] [MainThread]: Setting up your profile.
[0m18:24:31.781259 [error] [MainThread]: Encountered an error:

[0m18:24:31.791243 [error] [MainThread]: Traceback (most recent call last):
  File "/Users/adamworede/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dbt/cli/requires.py", line 161, in wrapper
    result, success = func(*args, **kwargs)
  File "/Users/adamworede/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dbt/cli/requires.py", line 111, in wrapper
    return func(*args, **kwargs)
  File "/Users/adamworede/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dbt/cli/main.py", line 483, in init
    results = task.run()
  File "/Users/adamworede/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dbt/task/init.py", line 346, in run
    self.setup_profile(profile_name)
  File "/Users/adamworede/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dbt/task/init.py", line 261, in setup_profile
    adapter = self.ask_for_adapter_choice()
  File "/Users/adamworede/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dbt/task/init.py", line 242, in ask_for_adapter_choice
    numeric_choice = click.prompt(prompt_msg, type=click.INT)
  File "/Users/adamworede/.pyenv/versions/3.10.12/lib/python3.10/site-packages/click/termui.py", line 164, in prompt
    value = prompt_func(prompt)
  File "/Users/adamworede/.pyenv/versions/3.10.12/lib/python3.10/site-packages/click/termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m18:24:31.799442 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 6.6141844, "process_in_blocks": "0", "process_kernel_time": 0.298379, "process_mem_max_rss": "98250752", "process_out_blocks": "0", "process_user_time": 2.393032}
[0m18:24:31.800997 [debug] [MainThread]: Command `dbt init` failed at 18:24:31.800747 after 6.62 seconds
[0m18:24:31.801926 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108ed17e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109da2410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109da4490>]}
[0m18:24:31.802799 [debug] [MainThread]: Flushing usage events
[0m18:24:32.429795 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m18:28:09.212338 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1057901f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106694e50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106694730>]}


============================== 18:28:09.222373 | 51f356ce-3520-44fa-8e4b-817d4592b2fc ==============================
[0m18:28:09.222373 [info ] [MainThread]: Running with dbt=1.10.5
[0m18:28:09.223233 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/adamworede/.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt init netflix_data', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m18:28:09.263306 [debug] [MainThread]: Starter project path: /Users/adamworede/Documents/netflix_snowflake_dbt/env/lib/python3.10/site-packages/dbt/include/starter_project
[0m18:28:09.272924 [info ] [MainThread]: 
Your new dbt project "netflix_data" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m18:28:09.274076 [info ] [MainThread]: Setting up your profile.
[0m18:31:34.599184 [info ] [MainThread]: Profile netflix_data written to /Users/adamworede/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m18:31:34.623053 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 205.55965, "process_in_blocks": "0", "process_kernel_time": 0.577334, "process_mem_max_rss": "114565120", "process_out_blocks": "0", "process_user_time": 2.942622}
[0m18:31:34.633285 [debug] [MainThread]: Command `dbt init` succeeded at 18:31:34.632332 after 205.57 seconds
[0m18:31:34.636931 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1057901f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106694b20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106697ac0>]}
[0m18:31:34.640910 [debug] [MainThread]: Flushing usage events
[0m18:31:35.316239 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m18:31:45.995398 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110668310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111571240>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111570b20>]}


============================== 18:31:46.005534 | 5e5e5989-ca41-4e01-a670-d40dd49cde4b ==============================
[0m18:31:46.005534 [info ] [MainThread]: Running with dbt=1.10.5
[0m18:31:46.006659 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/adamworede/.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt debug', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m18:31:46.047278 [info ] [MainThread]: dbt version: 1.10.5
[0m18:31:46.047991 [info ] [MainThread]: python version: 3.10.12
[0m18:31:46.048579 [info ] [MainThread]: python path: /Users/adamworede/Documents/netflix_snowflake_dbt/env/bin/python
[0m18:31:46.049131 [info ] [MainThread]: os info: macOS-15.5-x86_64-i386-64bit
[0m18:31:46.060815 [info ] [MainThread]: Error importing adapter: No module named 'dbt.adapters.bigquery'
[0m18:31:47.035888 [info ] [MainThread]: Using profiles dir at /Users/adamworede/.dbt
[0m18:31:47.036840 [info ] [MainThread]: Using profiles.yml file at /Users/adamworede/.dbt/profiles.yml
[0m18:31:47.037762 [info ] [MainThread]: Using dbt_project.yml file at /Users/adamworede/Documents/netflix_snowflake_dbt/dbt_project.yml
[0m18:31:47.038580 [info ] [MainThread]: Configuration:
[0m18:31:47.039216 [info ] [MainThread]:   profiles.yml file [[31mERROR invalid[0m]
[0m18:31:47.039800 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m18:31:47.040369 [info ] [MainThread]: Required dependencies:
[0m18:31:47.041058 [debug] [MainThread]: Executing "git --help"
[0m18:31:47.095697 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m18:31:47.097350 [debug] [MainThread]: STDERR: "b''"
[0m18:31:47.098011 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m18:31:47.098624 [info ] [MainThread]: Connection test skipped since no profile was found
[0m18:31:47.099395 [info ] [MainThread]: [31m2 checks failed:[0m
[0m18:31:47.099971 [info ] [MainThread]: Could not load dbt_project.yml
Profile loading failed for the following reason:
Runtime Error
  Credentials in profile "ecommerce_data", target "dev" invalid: Runtime Error
    Could not find adapter type bigquery!


[0m18:31:47.101018 [info ] [MainThread]: Project loading failed for the following reason:
 project path </Users/adamworede/Documents/netflix_snowflake_dbt/dbt_project.yml> not found

[0m18:31:47.107852 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 1.3480295, "process_in_blocks": "0", "process_kernel_time": 0.628062, "process_mem_max_rss": "116412416", "process_out_blocks": "0", "process_user_time": 3.630199}
[0m18:31:47.109691 [debug] [MainThread]: Command `dbt debug` failed at 18:31:47.109470 after 1.35 seconds
[0m18:31:47.110699 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110668310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111570190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1120c3850>]}
[0m18:31:47.111724 [debug] [MainThread]: Flushing usage events
[0m18:31:47.662981 [debug] [MainThread]: An error was encountered while trying to flush usage events
